---
- name: Create etcd cert directory
  ansible.builtin.file:
    path: "{{ etcd_cert_dir }}"
    state: directory
    mode: '0750'
  when:
    - inventory_hostname  in groups['kube_control_plane']

- name: Generate symlink to etcd certs
  ansible.builtin.file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
    force: true
  loop:
    - src: "{{etcd_cert_paths.client.ca}}"
      dest: "{{ etcd_cert_dir }}/{{kube_etcd_cacert_file}}"
    - src: "{{etcd_cert_paths.client.cert}}"
      dest: "{{ etcd_cert_dir }}/{{kube_etcd_cert_file}}"
    - src: "{{etcd_cert_paths.client.key}}"
      dest: "{{ etcd_cert_dir }}/{{kube_etcd_key_file}}"
  when:
    - inventory_hostname  in groups['kube_control_plane']
