---
# list of admission plugins that needs to be configured
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
kube_apiserver_admission_plugins_needs_configuration:
- EventRateLimit
- ImagePolicyWebhook
- PodSecurity
- PodNodeSelector
- ResourceQuota

kube_etcd_cacert_file: "kube-client-ca.pem"
kube_etcd_cert_file: "kube-client-cert.pem"
kube_etcd_key_file: "kube-client-key.pem"
